version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lunch_order_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/lunch_order_db
    ports:
      - '3001:3001'
    depends_on:
      - db

volumes:
  db-data:
